services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: custom-mysql:latest
    #image: mysql:9.3
    restart: always
    env_file:
      - ./.env.prod
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      #- ./init-scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      timeout: 10s
      retries: 30
      interval: 5s
      start_period: 40s
  
  db_ready:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: custom-mysql:latest
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.prod
    command: >
      bash -c "
      echo 'Waiting for stable query execution...';
      until mysql -h db -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1' >/dev/null 2>&1; do
        sleep 2;
      done;
      echo 'DB is fully query-ready';
      "
    restart: "no"

  asset_init:
    image: alpine:3.20
    volumes:
      - gallery_data:/gallery
      - images_data:/images
      - ./src/public/gallery:/seed/gallery:ro
      - ./src/public/images:/seed/images:ro
    command: >
      sh -c "
      echo 'Seeding assets...';
      [ -z \"$(ls -A /gallery 2>/dev/null)\" ] && cp -a /seed/gallery/. /gallery/;
      [ -z \"$(ls -A /images 2>/dev/null)\" ] && cp -a /seed/images/. /images/;
      echo 'Done';
      "
    restart: "no"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: arnies-cakes:latest
    command: ["node", "src/server.js"]
    env_file:
      - ./src/config/.env.dev
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    restart: always
    ports:
      - "3305:3305"
    volumes:
      - gallery_data:/usr/src/app/src/public/gallery
      - images_data:/usr/src/app/src/public/images
    depends_on:
      #db:
      #  condition: service_healthy
      db_ready:
        condition: service_completed_successfully
      asset_init:
        condition: service_completed_successfully

volumes:
  db_data:
  gallery_data:
  images_data: